export enum Router{
  INDEX = '/',
  MESSAGE = '/direct/inbox',
  PROFILE = '/profile',
  ACCOUNT_USER = '/account',
  SETTINGS= '/settings',
  EXPLORER= '/explorer',
  NOTIFICATION= '/notification',
  CREATE= '/create',
  SAVED = '/profile/saved',
  TAGGED= '/profile/tagged',
  EDIT_PROFILE= '/profile/edit',
  APP_AND_WEBSITE= '/profile/manage_access',
  PERSONAL_DETAIL= '/profile/personal_info',
  PASSWORD_AND_SECURITY= '/profile/password_and_security',
  WHAT_YOU_SEE ='/profile/what_you_see',
  WHO_CAN_SEE = '/profile/who_can_see_you',
  HELP= '/profile/help',
  EMAIL_NOTIFICATION= '/profile/emails/settings',
  PUSH_NOTIFICATION= 'profile/web/push/settings',
  SIGN_IN= '/account/login',
  SIGN_UP= '/account/signup',
  VERIFICATION ='/account/verification/email',
  LOADING_CONFIRMATION ='/account/isVerified',
  FORGOT_PASSWORD = '/account/password/reset',
  RESET_PASSWORD = '/password/reset_password_token',
  ERROR_NOT_FOUND= '*',
}

